# Generated by Django 5.1.8 on 2026-04-08 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatbotUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=64, unique=True)),
                (
                    "preset_state",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("awaiting_menstruating", "Awaiting Menstruating Answer"),
                            ("awaiting_last_period_date", "Awaiting Last Period Date"),
                            ("awaiting_has_ttd", "Awaiting Has TTD Answer"),
                            ("awaiting_reminder_hour", "Awaiting Reminder Hour"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=64,
                    ),
                ),
                (
                    "is_currently_menstruating",
                    models.BooleanField(blank=True, null=True),
                ),
                ("last_period_start_date", models.DateField(blank=True, null=True)),
                ("period_end_date", models.DateField(blank=True, null=True)),
                ("has_ttd_pill", models.BooleanField(blank=True, null=True)),
                (
                    "reminder_hour_24",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="InteractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_user_id", models.CharField(max_length=64)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("ai_qna", "AI QnA"),
                            ("preset_interaction", "Preset Interaction"),
                        ],
                        max_length=32,
                    ),
                ),
                ("endpoint", models.CharField(max_length=128)),
                ("user_message", models.TextField(blank=True)),
                ("bot_response", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("error", "Error")],
                        max_length=16,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interaction_logs",
                        to="chatbot.chatbotuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
